# ============================================================
# backend/agents/agent_orchestrator.py
# Agent 6 — Orchestrator Agent (Final Synthesis)
#
# Receives ALL validated outputs, deduplicates, structures
# the final report JSON, computes the Cyber Vulnerability
# Score (0-100), and produces executive-ready intelligence.
# Output: structured JSON → ready for React dashboard & PDF.
# ============================================================
import json
import anthropic
from datetime import datetime, timezone
from typing import Optional

from ..config import settings


ORCHESTRATOR_SYSTEM_PROMPT = """
You are Agent 6 — the Orchestrator Agent for BNP Paribas's Adverse News Platform.
You receive validated intelligence from all five prior agents and produce
the FINAL structured report that will be delivered to BNP Paribas decision-makers.

YOUR RESPONSIBILITIES:

1. COMPILE: Merge all validated findings into a coherent, deduplicated report.
2. SCORE: Compute the final Cyber Vulnerability Score (0-100) using the formula:
   - Legal & Integrity (Agent 2): 35% weight
   - Executive & Reputation (Agent 3): 20% weight
   - Operations & Finance (Agent 4): 30% weight
   - Evidence Quality Bonus/Penalty (Agent 5): ±15%
   Formula: (legal * 0.35) + (executive * 0.20) + (operations * 0.30) + evidence_adjustment
   Round to nearest integer. Cap at 100.

3. RISK LEVEL: Assign based on final score:
   - 0-30: LOW
   - 31-64: MEDIUM
   - 65-100: HIGH

4. STRUCTURE: Organize into 6 predefined sections matching the 6-pillar framework.

5. EXECUTIVE SUMMARY: Write a crisp 3-sentence executive summary for top management.

6. TOP ISSUES: List the 3-5 most critical findings as concise labels (e.g., "Money Laundering",
   "Data Breach", "$4.3B Regulatory Fine").

7. DECISION INTELLIGENCE: Provide a clear recommended action:
   AVOID — Do not engage / terminate existing relationship
   CAUTION — Engage with enhanced due diligence and monitoring
   MONITOR — Continue relationship with periodic adverse news checks
   CLEAR — No significant adverse signals found

OUTPUT ONLY valid JSON. This is the final deliverable.

OUTPUT FORMAT:
{
  "report_metadata": {
    "generated_at": "ISO timestamp",
    "platform": "Adverse News Platform — BNP Paribas",
    "data_cutoff": "2020-01-01",
    "report_version": "1.0",
    "evidence_quality": "HIGH | MEDIUM | LOW"
  },
  "company_profile": {
    "name": "...",
    "domain": "...",
    "country": "...",
    "sector": "...",
    "founded": "..."
  },
  "executive_summary": "Three-sentence executive summary for top management.",
  "cyber_vulnerability_score": 87,
  "risk_level": "HIGH",
  "score_breakdown": {
    "legal_integrity_score": 85,
    "legal_weight": 0.35,
    "executive_reputation_score": 70,
    "executive_weight": 0.20,
    "operations_finance_score": 92,
    "operations_weight": 0.30,
    "evidence_quality_adjustment": 5,
    "formula_applied": "(85*0.35) + (70*0.20) + (92*0.30) + 5 = 87"
  },
  "top_issues": ["Money Laundering", "$4.35B CFTC Fine", "AML Non-Compliance", "Data Breach"],
  "decision_intelligence": "AVOID",
  "decision_rationale": "Two-sentence rationale for the recommendation.",
  "pillar_analysis": {
    "pillar1_regulatory_legal": {
      "score": 85,
      "key_findings": [...],
      "summary": "..."
    },
    "pillar2_financial_crime": {
      "score": 90,
      "key_findings": [...],
      "summary": "..."
    },
    "pillar3_executive_risk": {
      "score": 65,
      "key_findings": [...],
      "summary": "..."
    },
    "pillar4_operational_security": {
      "score": 75,
      "key_findings": [...],
      "summary": "..."
    },
    "pillar5_financial_health": {
      "score": 40,
      "key_findings": [...],
      "summary": "..."
    },
    "pillar6_ethical_reputational": {
      "score": 70,
      "key_findings": [...],
      "summary": "..."
    }
  },
  "verified_signals_count": 12,
  "rejected_signals_count": 2,
  "key_risk_flags": ["OFAC Exposure", "Platform Insolvency"],
  "monitoring_recommendations": ["Re-analyze in 30 days", "Watch for DOJ proceedings"],
  "disclaimer": "This report is generated by an AI system for internal BNP Paribas use only. It does not constitute legal advice. All findings should be validated by the Compliance team before action."
}
"""


async def run_orchestrator_agent(
    company_name: str,
    domain: Optional[str],
    triage_data: dict,
    legal_analysis: dict,
    executive_analysis: dict,
    operations_analysis: dict,
    evidence_validation: dict,
) -> dict:
    """
    Agent 6: Final synthesis — produces the complete structured report + CVS score.
    """
    client = anthropic.Anthropic(api_key=settings.ANTHROPIC_API_KEY)

    # Extract validated scores
    score_validation = evidence_validation.get("score_validation", {})
    legal_score = score_validation.get("legal_score_validated",
                                       legal_analysis.get("legal_risk_score", 0))
    exec_score = score_validation.get("executive_score_validated",
                                      executive_analysis.get("combined_score", 0))
    ops_score = score_validation.get("operations_score_validated",
                                     operations_analysis.get("combined_score", 0))

    user_message = f"""
Produce the FINAL intelligence report for: {company_name}
Domain: {domain or "unknown"}
Report Generation: {datetime.now(timezone.utc).isoformat()}

=== VALIDATED SCORES ===
Legal & Integrity Score: {legal_score} / 100
Executive & Reputation Score: {exec_score} / 100
Operations & Finance Score: {ops_score} / 100
Evidence Quality: {evidence_validation.get("overall_evidence_quality", "MEDIUM")}

=== EVIDENCE AGENT VALIDATION ===
Verified Top Issues: {evidence_validation.get("verified_top_issues", [])}
Verified Key Flags: {evidence_validation.get("verified_key_flags", [])}
Validation Summary: {evidence_validation.get("validation_summary", "")}
Rejected Findings Count: {len(evidence_validation.get("rejected_findings", []))}

=== LEGAL FINDINGS SUMMARY ===
Recommendation: {legal_analysis.get("recommendation", "UNKNOWN")}
Key Flags: {legal_analysis.get("key_risk_flags", [])}
Narrative: {legal_analysis.get("risk_narrative", "")[:500]}

=== EXECUTIVE FINDINGS SUMMARY ===
Recommendation: {executive_analysis.get("recommendation", "UNKNOWN")}
Key Flags: {executive_analysis.get("key_risk_flags", [])}

=== OPERATIONS FINDINGS SUMMARY ===
Recommendation: {operations_analysis.get("recommendation", "UNKNOWN")}
Key Flags: {operations_analysis.get("key_risk_flags", [])}

=== TRIAGE CONTEXT ===
Total Signals: {triage_data.get("total_signals", 0)}
Highest Severity: {triage_data.get("highest_severity", 0)}
Triage Summary: {triage_data.get("triage_summary", "")}

Compute the final Cyber Vulnerability Score using the weighted formula.
Compile the complete final report JSON. Make the executive summary sharp
and actionable for a BNP Paribas Risk Director.
"""

    response = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=5000,
        system=ORCHESTRATOR_SYSTEM_PROMPT,
        messages=[{"role": "user", "content": user_message}],
    )

    result = _parse_response(response.content[0].text, company_name)

    # Ensure critical fields exist
    if "cyber_vulnerability_score" not in result:
        # Compute fallback score
        evidence_adj = 5 if evidence_validation.get("overall_evidence_quality") == "HIGH" else 0
        fallback_score = round(
            (legal_score * 0.35) + (exec_score * 0.20) + (ops_score * 0.30) + evidence_adj
        )
        result["cyber_vulnerability_score"] = min(100, fallback_score)

    score = result["cyber_vulnerability_score"]
    if "risk_level" not in result:
        result["risk_level"] = (
            "HIGH" if score >= 65
            else "MEDIUM" if score >= 31
            else "LOW"
        )

    return result


def _parse_response(raw_text: str, company: str) -> dict:
    raw_text = raw_text.strip()
    if raw_text.startswith("```"):
        parts = raw_text.split("```")
        raw_text = parts[1] if len(parts) > 1 else raw_text
        if raw_text.startswith("json"):
            raw_text = raw_text[4:]
    try:
        return json.loads(raw_text)
    except json.JSONDecodeError:
        return {
            "company_profile": {"name": company},
            "cyber_vulnerability_score": 0,
            "risk_level": "UNKNOWN",
            "executive_summary": "Report generation encountered an error.",
            "top_issues": [],
            "decision_intelligence": "CAUTION",
            "pillar_analysis": {},
            "error": "JSON parse failed",
            "_raw": raw_text[:500],
        }
