# ============================================================
# backend/services/pdf_service.py
# PDF Report Generator using ReportLab
# Produces a professional BNP Paribas-branded PDF
# ============================================================
import os
import json
from datetime import datetime, timezone
from typing import Optional
from pathlib import Path

# ReportLab
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, KeepTogether,
)
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT, TA_JUSTIFY

# ---- Constants -------------------------------------------------------
REPORTS_DIR = Path("./reports_pdf")
REPORTS_DIR.mkdir(exist_ok=True)

# BNP Paribas Brand Colors
BNP_GREEN = colors.HexColor("#00915A")
BNP_DARK = colors.HexColor("#1C2438")
BNP_CHARCOAL = colors.HexColor("#2D2D2D")
BNP_LIGHT = colors.HexColor("#F4F4F8")
RED = colors.HexColor("#D32F2F")
ORANGE = colors.HexColor("#F57C00")
GREEN_SAFE = colors.HexColor("#388E3C")
GREY = colors.HexColor("#7A7A8A")
BORDER = colors.HexColor("#E2E2EC")


def _get_risk_color(risk_level: str) -> colors.Color:
    mapping = {"HIGH": RED, "MEDIUM": ORANGE, "LOW": GREEN_SAFE}
    return mapping.get(risk_level.upper(), GREY)


def _get_score_color(score: float) -> colors.Color:
    if score >= 65:
        return RED
    elif score >= 31:
        return ORANGE
    return GREEN_SAFE


async def generate_report_pdf(report_id: int, final_report: dict) -> str:
    """Generate a PDF from the final orchestrator report. Returns the file path."""
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    company_slug = (
        final_report.get("company_profile", {})
        .get("name", "Unknown")
        .replace(" ", "_")
        .replace("/", "-")[:30]
    )
    filename = f"ANP_{company_slug}_{timestamp}.pdf"
    filepath = REPORTS_DIR / filename

    doc = SimpleDocTemplate(
        str(filepath),
        pagesize=A4,
        rightMargin=20 * mm,
        leftMargin=20 * mm,
        topMargin=20 * mm,
        bottomMargin=20 * mm,
    )

    styles = _build_styles()
    story = []

    # ---- HEADER --------------------------------------------------------
    _add_header(story, styles, final_report)

    # ---- EXECUTIVE SUMMARY ---------------------------------------------
    _add_section(story, styles, "Executive Summary",
                 final_report.get("executive_summary", "No summary available."))

    # ---- SCORE + DECISION BOX ------------------------------------------
    _add_score_table(story, styles, final_report)

    # ---- TOP ISSUES ----------------------------------------------------
    top_issues = final_report.get("top_issues", [])
    if top_issues:
        story.append(Spacer(1, 6))
        story.append(Paragraph("Key Adverse Signals Identified", styles["section_title"]))
        story.append(HRFlowable(width="100%", thickness=1, color=BORDER, spaceAfter=6))
        for issue in top_issues:
            story.append(Paragraph(f"• {issue}", styles["bullet"]))
        story.append(Spacer(1, 10))

    # ---- PILLAR ANALYSIS -----------------------------------------------
    pillar_analysis = final_report.get("pillar_analysis", {})
    if pillar_analysis:
        story.append(Paragraph("6-Pillar Risk Analysis", styles["section_title"]))
        story.append(HRFlowable(width="100%", thickness=1, color=BORDER, spaceAfter=6))
        _add_pillar_table(story, styles, pillar_analysis)
        story.append(Spacer(1, 10))

    # ---- DECISION INTELLIGENCE -----------------------------------------
    decision = final_report.get("decision_intelligence", "CAUTION")
    rationale = final_report.get("decision_rationale", "")
    _add_decision_box(story, styles, decision, rationale)

    # ---- MONITORING RECOMMENDATIONS ------------------------------------
    monitoring = final_report.get("monitoring_recommendations", [])
    if monitoring:
        story.append(Spacer(1, 6))
        story.append(Paragraph("Monitoring Recommendations", styles["section_title"]))
        story.append(HRFlowable(width="100%", thickness=1, color=BORDER, spaceAfter=6))
        for rec in monitoring:
            story.append(Paragraph(f"→ {rec}", styles["bullet"]))
        story.append(Spacer(1, 10))

    # ---- DISCLAIMER ----------------------------------------------------
    disclaimer = final_report.get(
        "disclaimer",
        "This report is generated by an AI system for internal BNP Paribas use only."
    )
    story.append(Spacer(1, 10))
    story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER))
    story.append(Spacer(1, 4))
    story.append(Paragraph(disclaimer, styles["disclaimer"]))

    doc.build(story, onFirstPage=_add_page_border, onLaterPages=_add_page_border)
    return str(filepath)


def _build_styles() -> dict:
    base = getSampleStyleSheet()
    styles = {}

    styles["title"] = ParagraphStyle(
        "title", fontSize=20, fontName="Helvetica-Bold",
        textColor=BNP_DARK, spaceAfter=4,
    )
    styles["subtitle"] = ParagraphStyle(
        "subtitle", fontSize=10, fontName="Helvetica",
        textColor=GREY, spaceAfter=12,
    )
    styles["section_title"] = ParagraphStyle(
        "section_title", fontSize=11, fontName="Helvetica-Bold",
        textColor=BNP_DARK, spaceBefore=12, spaceAfter=4,
    )
    styles["body"] = ParagraphStyle(
        "body", fontSize=9, fontName="Helvetica",
        textColor=BNP_CHARCOAL, leading=14, alignment=TA_JUSTIFY,
    )
    styles["bullet"] = ParagraphStyle(
        "bullet", fontSize=9, fontName="Helvetica",
        textColor=BNP_CHARCOAL, leading=13, leftIndent=12,
    )
    styles["score_big"] = ParagraphStyle(
        "score_big", fontSize=36, fontName="Helvetica-Bold",
        alignment=TA_CENTER,
    )
    styles["label"] = ParagraphStyle(
        "label", fontSize=8, fontName="Helvetica-Bold",
        textColor=GREY, alignment=TA_CENTER, spaceAfter=2,
    )
    styles["disclaimer"] = ParagraphStyle(
        "disclaimer", fontSize=7.5, fontName="Helvetica",
        textColor=GREY, leading=11, alignment=TA_JUSTIFY,
    )
    styles["pillar_name"] = ParagraphStyle(
        "pillar_name", fontSize=8.5, fontName="Helvetica-Bold",
        textColor=BNP_DARK,
    )
    styles["pillar_body"] = ParagraphStyle(
        "pillar_body", fontSize=8, fontName="Helvetica",
        textColor=BNP_CHARCOAL, leading=12,
    )
    return styles


def _add_header(story, styles, report: dict):
    company = report.get("company_profile", {})
    company_name = company.get("name", "Unknown Company")
    generated_at = report.get("report_metadata", {}).get(
        "generated_at",
        datetime.now(timezone.utc).isoformat()
    )

    # Title row
    story.append(Paragraph("ADVERSE NEWS PLATFORM", styles["subtitle"]))
    story.append(Paragraph(f"Intelligence Report: {company_name}", styles["title"]))

    meta_data = [
        ["Domain", company.get("domain", "—"),
         "Country", company.get("country", "—")],
        ["Sector", company.get("sector", "—"),
         "Generated", generated_at[:10]],
        ["Classification", "INTERNAL — CONFIDENTIAL",
         "Platform", "BNP Paribas ANP v1.0"],
    ]

    meta_table = Table(meta_data, colWidths=[30 * mm, 55 * mm, 25 * mm, 55 * mm])
    meta_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (2, 0), (2, -1), "Helvetica-Bold"),
        ("TEXTCOLOR", (0, 0), (0, -1), GREY),
        ("TEXTCOLOR", (2, 0), (2, -1), GREY),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
    ]))
    story.append(Spacer(1, 6))
    story.append(meta_table)
    story.append(HRFlowable(width="100%", thickness=2, color=BNP_GREEN, spaceBefore=8, spaceAfter=12))


def _add_section(story, styles, title: str, content: str):
    story.append(Paragraph(title, styles["section_title"]))
    story.append(HRFlowable(width="100%", thickness=1, color=BORDER, spaceAfter=6))
    story.append(Paragraph(content, styles["body"]))
    story.append(Spacer(1, 8))


def _add_score_table(story, styles, report: dict):
    score = report.get("cyber_vulnerability_score", 0)
    risk_level = report.get("risk_level", "UNKNOWN")
    decision = report.get("decision_intelligence", "CAUTION")
    evidence_quality = report.get("report_metadata", {}).get("evidence_quality", "MEDIUM")

    score_color = _get_score_color(score)
    risk_color = _get_risk_color(risk_level)

    decision_colors = {
        "AVOID": RED,
        "CAUTION": ORANGE,
        "MONITOR": colors.HexColor("#1565C0"),
        "CLEAR": GREEN_SAFE,
    }
    decision_color = decision_colors.get(decision.upper(), GREY)

    score_para = Paragraph(
        f'<font color="#{score_color.hexval()[2:]}"><b>{score}</b></font>',
        styles["score_big"]
    )

    data = [[
        [Paragraph("CYBER VULNERABILITY SCORE", styles["label"]), score_para,
         Paragraph("/ 100", styles["label"])],
        [Paragraph("RISK LEVEL", styles["label"]),
         Paragraph(f'<font color="#{risk_color.hexval()[2:]}"><b>{risk_level}</b></font>',
                   ParagraphStyle("rl", fontSize=18, fontName="Helvetica-Bold",
                                  alignment=TA_CENTER))],
        [Paragraph("DECISION", styles["label"]),
         Paragraph(f'<font color="#{decision_color.hexval()[2:]}"><b>{decision}</b></font>',
                   ParagraphStyle("dec", fontSize=14, fontName="Helvetica-Bold",
                                  alignment=TA_CENTER))],
        [Paragraph("EVIDENCE QUALITY", styles["label"]),
         Paragraph(f"<b>{evidence_quality}</b>",
                   ParagraphStyle("eq", fontSize=12, fontName="Helvetica-Bold",
                                  alignment=TA_CENTER, textColor=GREY))],
    ]]

    flat_data = [
        [score_para, risk_level, decision, evidence_quality],
    ]
    header_row = ["CVS Score", "Risk Level", "Decision", "Evidence Quality"]

    table = Table([header_row, flat_data[0]], colWidths=[42 * mm, 42 * mm, 42 * mm, 42 * mm])
    table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 7),
        ("TEXTCOLOR", (0, 0), (-1, 0), GREY),
        ("FONTNAME", (0, 1), (-1, 1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 1), (0, 1), 28),
        ("FONTSIZE", (1, 1), (-1, 1), 14),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("BACKGROUND", (0, 0), (-1, -1), BNP_LIGHT),
        ("TEXTCOLOR", (0, 1), (0, 1), score_color),
        ("TEXTCOLOR", (1, 1), (1, 1), risk_color),
        ("TEXTCOLOR", (2, 1), (2, 1), decision_color),
        ("GRID", (0, 0), (-1, -1), 0.5, BORDER),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("ROUNDEDCORNERS", [4]),
    ]))

    story.append(Spacer(1, 6))
    story.append(table)
    story.append(Spacer(1, 10))


def _add_pillar_table(story, styles, pillar_analysis: dict):
    pillar_labels = {
        "pillar1_regulatory_legal": "1. Regulatory & Legal",
        "pillar2_financial_crime": "2. Financial Crime",
        "pillar3_executive_risk": "3. Executive Risk",
        "pillar4_operational_security": "4. Operational & Cyber",
        "pillar5_financial_health": "5. Financial Health",
        "pillar6_ethical_reputational": "6. Ethical & Reputational",
    }

    rows = [["Pillar", "Score", "Summary"]]
    for key, label in pillar_labels.items():
        pillar = pillar_analysis.get(key, {})
        score = pillar.get("score", "—")
        summary = pillar.get("summary", "No data available.")[:150]
        score_color = _get_score_color(float(score)) if isinstance(score, (int, float)) else GREY
        rows.append([label, str(score), summary])

    table = Table(rows, colWidths=[45 * mm, 18 * mm, 102 * mm])
    style = [
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("BACKGROUND", (0, 0), (-1, 0), BNP_DARK),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("ALIGN", (1, 0), (1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("GRID", (0, 0), (-1, -1), 0.5, BORDER),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, BNP_LIGHT]),
        ("FONTNAME", (0, 1), (0, -1), "Helvetica-Bold"),
        ("TEXTCOLOR", (0, 1), (0, -1), BNP_DARK),
    ]

    # Color-code score column
    for i, row in enumerate(rows[1:], start=1):
        try:
            s = float(row[1])
            col = _get_score_color(s)
            style.append(("TEXTCOLOR", (1, i), (1, i), col))
            style.append(("FONTNAME", (1, i), (1, i), "Helvetica-Bold"))
        except (ValueError, TypeError):
            pass

    table.setStyle(TableStyle(style))
    story.append(table)


def _add_decision_box(story, styles, decision: str, rationale: str):
    decision_colors = {
        "AVOID": (RED, colors.HexColor("#FFEBEE")),
        "CAUTION": (ORANGE, colors.HexColor("#FFF3E0")),
        "MONITOR": (colors.HexColor("#1565C0"), colors.HexColor("#E3F2FD")),
        "CLEAR": (GREEN_SAFE, colors.HexColor("#E8F5E9")),
    }
    fg, bg = decision_colors.get(decision.upper(), (GREY, BNP_LIGHT))

    decision_icons = {
        "AVOID": "🚫",
        "CAUTION": "⚠️",
        "MONITOR": "👁️",
        "CLEAR": "✅",
    }

    data = [[
        Paragraph(f"<b>DECISION INTELLIGENCE: {decision}</b>",
                  ParagraphStyle("dec_title", fontSize=11, fontName="Helvetica-Bold",
                                 textColor=fg)),
        Paragraph(rationale or "No rationale provided.",
                  ParagraphStyle("dec_body", fontSize=9, fontName="Helvetica",
                                 textColor=BNP_CHARCOAL, leading=13)),
    ]]
    table = Table(data, colWidths=[65 * mm, 100 * mm])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), bg),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LINEABOVE", (0, 0), (-1, 0), 2, fg),
        ("LINEBELOW", (0, -1), (-1, -1), 2, fg),
    ]))
    story.append(table)


def _add_page_border(canvas, doc):
    """Draw header/footer on every page."""
    canvas.saveState()
    width, height = A4

    # Top bar
    canvas.setFillColor(BNP_DARK)
    canvas.rect(0, height - 12 * mm, width, 12 * mm, fill=1, stroke=0)
    canvas.setFillColor(BNP_GREEN)
    canvas.rect(0, height - 12 * mm, 4 * mm, 12 * mm, fill=1, stroke=0)
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 9)
    canvas.drawString(10 * mm, height - 8 * mm, "ADVERSE NEWS PLATFORM")
    canvas.setFont("Helvetica", 8)
    canvas.drawRightString(
        width - 10 * mm, height - 8 * mm,
        f"BNP Paribas · INTERNAL & CONFIDENTIAL · Page {doc.page}"
    )

    # Bottom bar
    canvas.setFillColor(BNP_LIGHT)
    canvas.rect(0, 0, width, 8 * mm, fill=1, stroke=0)
    canvas.setFillColor(BNP_GREEN)
    canvas.rect(0, 0, width, 1 * mm, fill=1, stroke=0)
    canvas.setFillColor(GREY)
    canvas.setFont("Helvetica", 7)
    canvas.drawString(
        10 * mm, 3 * mm,
        f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')} · "
        "Classification: Internal · Not for external distribution"
    )

    canvas.restoreState()
